# Generated by Django 4.2.3 on 2023-07-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayBasedPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceWithBreakPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakPoint", models.FloatField()),
                ("preBreakPointPrice", models.FloatField()),
                ("postBreakPointPrice", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TimeMultiplierFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakPoint1", models.FloatField()),
                ("breakPoint2", models.FloatField()),
                ("preBreakPointPrice", models.FloatField()),
                ("midBreakPointPrice", models.FloatField()),
                ("endBreakPointPrice", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DAP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DAP",
                        to="upload_price.pricewithbreakpoint",
                    ),
                ),
                (
                    "DBP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DBP",
                        to="upload_price.daybasedpricing",
                    ),
                ),
                (
                    "TMF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TMF",
                        to="upload_price.timemultiplierfactor",
                    ),
                ),
                (
                    "WC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="WC",
                        to="upload_price.pricewithbreakpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Friday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Monday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Saturday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Sunday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sunday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Thursday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thursday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Tuesday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuesday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
        migrations.AddField(
            model_name="daybasedpricing",
            name="Wednesday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wednesday",
                to="upload_price.pricewithbreakpoint",
            ),
        ),
    ]
