# Generated by Django 4.2.3 on 2023-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_price", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceconfig",
            name="isLive",
            field=models.BooleanField(default=False),
        ),
    ]
