# Generated by Django 4.2.3 on 2023-07-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_price", "0002_priceconfig_islive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="priceconfig", old_name="isLive", new_name="IsLive",
        ),
    ]
