# Generated by Django 4.2.3 on 2023-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_price", "0003_rename_islive_priceconfig_islive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priceconfig",
            name="IsLive",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
